### ISSUE TITLE
Clean checkout does not compile with "org.junit does not exist" errors

### ISSUE THREAD

**Issue by pataprogramming** [Netflix/zuul#95]
With a fresh checkout of commit 25ee80368500dd46671fcceb4b4aa6f653b59f66, Zuul is unable to build on my system (Ubuntu 14.04.1 with Oracle JDK 1.7.0_72). Builds fail with dozens of missing package errors along the lines of

```
:zuul-netflix:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
/home/user/foreign-repos/zuul/zuul-netflix/src/main/java/com/netflix/zuul/scriptManager/FilterVerifier.java:22: error: package org.junit does not exist
import org.junit.Before;
                ^
/home/user/foreign-repos/zuul/zuul-netflix/src/main/java/com/netflix/zuul/scriptManager/FilterVerifier.java:23: error: package org.junit does not exist
import org.junit.Test;
                ^
/home/user/foreign-repos/zuul/zuul-netflix/src/main/java/com/netflix/zuul/scriptManager/FilterVerifier.java:26: error: package org.junit does not exist
import static org.junit.Assert.*;
                ^
```

These failures occur in both the `zuul-netflix` subdirectory and the `zuul-netflix-webapp` subdirectory (once the former is fixed). Copying the following line from `zuul-core/build.gradle` to the `build.gradle` files in the failing subdirectories allows everything to compile (though I'm not sure if this is the correct way to fix this properly):

```
provided 'junit:junit-dep:4.10'
```
